### ISSUE TITLE
No suitable driver found

### ISSUE THREAD

**Issue by TSEMCC** [shaxxx/Xamarin.jTDS#1]
Hi,

When running your example project i get an exception at "con = DriverManager.GetConnection (connString, username, password);" : No suitable driver found for "ConnectionString"

What am I doing wrong??

**Comment by shaxxx** [comment]
First thing that comes to my mind is 
- wrong or non existing driver (example uses Net.Sourceforge.Jtds.Jdbc;)
-wrong jTDS version

But why would you use jTDS anyway? This project was created when only Xamarin Professional license included SqlConnection namespac, and it costed a LOT. 

These days it's freely available and you can use SqlConnection classes like you would on any .NET Standard 2.0 project. Ditch the jTDS, no sense in putting stuff in your APK to get functionality that is already there.

**Comment by TSEMCC** [comment]
Hey,
Thank you for your quick response. 
I want to authenticate users with integrated security over MSSQL. Imho it is not available by default at the moment. From the jTDS Doku:

"domain:
Specifies the Windows domain to authenticate in. If present and the user name and password are provided, jTDS uses Windows (NTLM) authentication instead of the usual SQL Server authentication (i.e. the user and password provided are the domain user and password). This allows non-Windows clients to log in to servers which are only configured to accept Windoes authentication."

So its not possible with your Project? 

Thanks in Advance

**Comment by shaxxx** [comment]
Project is simple binding to provide you with jTDS funcionality, what's supported in jTDS is available.
Again, did you try with .NET SqlConnection class. Only reason why I created this project is that SqlConnection goodness was not available at that time.

**Comment by TSEMCC** [comment]
Yes, but there´s no functionality to pass Windows Credentials. Just workes for local SQL users.... From the Docu of jTDS i thought it will be possible over NTLM with this driver.

**Comment by acaliaro** [comment]
Hi @shaxxx 

I have the same problem.. "No suitable driver". You are right, now Xamarin has System.Data.SqlClient but it does not work with SQLSERVER 2000 because I use .NETStandard. So I would like to use your library.

The strange thing is that if I use your demo on an Android TC51 Zebra Device (Android 6), it works perfectly. The same code on an Android TC25 Zebra Device (Android 7) gives the error.

Do you have some ideas about it?
Thanks

**Comment by acaliaro** [comment]
@TSEMCC have you found a solution for this?
